<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\JobSearchController;
use App\Http\Controllers\ConversationController;
use App\Http\Controllers\EmployerWorkspaceController;
use App\Http\Controllers\JobApplicationController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\JobCategoryController;
use App\Http\Controllers\EmployerReviewController;

Route::get('/', [AuthController::class, 'home'])->name('home');
Route::get('/jobs', [AuthController::class, 'searchPage'])->name('jobs.page');
Route::get('/profile', [AuthController::class, 'profilePage'])->middleware(['auth', 'active.account'])->name('profile.page');
Route::get('/api/jobs/search', [JobSearchController::class, 'index'])->name('jobs.search');
Route::get('/api/jobs/{jobId}', [JobApplicationController::class, 'show'])->whereNumber('jobId')->name('jobs.show');
Route::get('/api/job-categories', [JobCategoryController::class, 'index'])->name('job-categories.index');
Route::get('/api/employers/{employer}/reviews', [EmployerReviewController::class, 'publicForEmployer'])->name('employer-reviews.index');

Route::get('/login', [AuthController::class, 'showLogin'])->middleware('guest')->name('login');
Route::post('/login', [AuthController::class, 'login'])->middleware('guest')->name('login.store');
Route::get('/register', [AuthController::class, 'showRegister'])->middleware('guest')->name('register');
Route::post('/register', [AuthController::class, 'register'])->middleware('guest')->name('register.store');
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::patch('/profile', [AuthController::class, 'updateProfile'])->middleware(['auth', 'active.account'])->name('profile.update');
Route::get('/profile/resume', [AuthController::class, 'downloadResume'])->middleware(['auth', 'active.account'])->name('profile.resume');

Route::middleware(['auth', 'active.account'])->prefix('api')->group(function () {
    Route::post('/reports', [AdminController::class, 'report'])->middleware('throttle:5,1')->name('reports.store');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::patch('/notifications/read-all', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::patch('/notifications/{notification}/read', [NotificationController::class, 'markRead'])->name('notifications.read');
    Route::delete('/notifications/{notification}', [NotificationController::class, 'destroy'])->name('notifications.destroy');
    Route::get('/employer/billing', [BillingController::class, 'overview'])->name('employer.billing');
    Route::post('/employer/billing/orders', [BillingController::class, 'createOrder'])->middleware('throttle:10,1')->name('employer.billing.orders.store');
    Route::post('/employer/billing/orders/{order}/payments', [BillingController::class, 'submitPayment'])->middleware('throttle:5,1')->name('employer.billing.payments.store');
    Route::get('/billing/invoices/{invoice}', [BillingController::class, 'invoice'])->name('billing.invoices.show');
    Route::get('/admin/billing/payments', [BillingController::class, 'adminPayments'])->name('admin.billing.payments');
    Route::get('/admin/billing/payments/{payment}/proof', [BillingController::class, 'paymentProof'])->name('admin.billing.payments.proof');
    Route::patch('/admin/billing/payments/{payment}/review', [BillingController::class, 'reviewPayment'])->name('admin.billing.payments.review');
    Route::post('/admin/billing/payments/{payment}/refunds', [BillingController::class, 'recordRefund'])->name('admin.billing.payments.refunds.store');
    Route::prefix('/admin')->name('admin.')->group(function () {
        Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
        Route::get('/users', [AdminController::class, 'users'])->name('users');
        Route::patch('/users/{user}', [AdminController::class, 'updateUser'])->name('users.update');
        Route::get('/employers', [AdminController::class, 'employers'])->name('employers');
        Route::patch('/employers/{employer}/verification', [AdminController::class, 'reviewEmployer'])->name('employers.verification');
        Route::get('/jobs', [AdminController::class, 'jobs'])->name('jobs');
        Route::patch('/jobs/{job}/moderation', [AdminController::class, 'moderateJob'])->name('jobs.moderation');
        Route::get('/applications', [AdminController::class, 'applications'])->name('applications');
        Route::get('/reports', [AdminController::class, 'reports'])->name('reports');
        Route::patch('/reports/{report}', [AdminController::class, 'reviewReport'])->name('reports.review');
        Route::get('/categories', [AdminController::class, 'categories'])->name('categories');
        Route::post('/categories', [AdminController::class, 'createCategory'])->name('categories.store');
        Route::patch('/categories/{jobCategory}', [AdminController::class, 'updateCategory'])->name('categories.update');
        Route::get('/employer-reviews', [AdminController::class, 'reviews'])->name('employer-reviews');
        Route::patch('/employer-reviews/{employerReview}', [AdminController::class, 'moderateReview'])->name('employer-reviews.moderate');
        Route::get('/audit-logs', [AdminController::class, 'auditLogs'])->name('audit-logs');
    });
    Route::get('/employer/talent', [BillingController::class, 'talent'])->name('employer.talent');
    Route::get('/employer/talent/{jobSeekerId}/resume', [BillingController::class, 'downloadTalentResume'])->whereNumber('jobSeekerId')->name('employer.talent.resume');
    Route::post('/jobs/{jobId}/applications', [JobApplicationController::class, 'apply'])->whereNumber('jobId')->middleware('throttle:10,1')->name('applications.store');
    Route::post('/applications/{application}/employer-review', [EmployerReviewController::class, 'store'])->middleware('throttle:5,1')->name('employer-reviews.store');
    Route::post('/jobs/{jobId}/save', [JobApplicationController::class, 'save'])->whereNumber('jobId')->name('jobs.save');
    Route::delete('/jobs/{jobId}/save', [JobApplicationController::class, 'unsave'])->whereNumber('jobId')->name('jobs.unsave');
    Route::get('/employer/dashboard', [EmployerWorkspaceController::class, 'dashboard'])->name('employer.dashboard');
    Route::patch('/employer/profile', [EmployerWorkspaceController::class, 'updateProfile'])->name('employer.profile.update');
    Route::post('/employer/verification', [EmployerWorkspaceController::class, 'requestVerification'])->middleware('throttle:5,1')->name('employer.verification.request');
    Route::get('/employer/candidates', [EmployerWorkspaceController::class, 'candidates'])->name('employer.candidates');
    Route::post('/employer/jobs', [EmployerWorkspaceController::class, 'createJob'])->name('employer.jobs.store');
    Route::patch('/employer/jobs/{job}', [EmployerWorkspaceController::class, 'updateJob'])->name('employer.jobs.update');
    Route::delete('/employer/jobs/{job}', [EmployerWorkspaceController::class, 'deleteJob'])->name('employer.jobs.destroy');
    Route::patch('/employer/applications/{application}', [EmployerWorkspaceController::class, 'updateApplication'])->name('employer.applications.update');
    Route::get('/employer/applications/{application}/resume', [EmployerWorkspaceController::class, 'downloadResume'])->name('employer.applications.resume');
    Route::post('/employer/applications/{application}/interviews', [EmployerWorkspaceController::class, 'scheduleInterview'])->name('employer.applications.interviews.store');
    Route::get('/conversations', [ConversationController::class, 'index'])->name('conversations.index');
    Route::post('/applications/{application}/conversation', [ConversationController::class, 'startForApplication'])->middleware('throttle:20,1')->name('conversations.start');
    Route::get('/conversations/{conversation}/messages', [ConversationController::class, 'messages'])->name('conversations.messages');
    Route::post('/conversations/{conversation}/messages', [ConversationController::class, 'storeMessage'])->middleware('throttle:30,1')->name('conversations.messages.store');
    Route::patch('/conversations/{conversation}/read', [ConversationController::class, 'markRead'])->name('conversations.read');
    Route::get('/message-attachments/{attachment}', [ConversationController::class, 'attachment'])->name('message-attachments.show');
});
